apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-pipelinerun-
spec:
  pipelineRef:
    name: build-and-deploy
  resources:
    - name: sample-repo
      resourceRef:
        name: sample-repo
    - name: sample-image
      resourceRef:
        name: sample-image
